### PR TITLE
Add vendor folder

### PR DESCRIPTION
**Pull request by jingxu97**
add vendor folder

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @msau42

**Review by ddebroy — COMMENTED** [review]
@jingxu97 is the vendor/modules.txt file missing? https://golang.org/ref/mod#vendoring

**Comment by jingxu97** [comment]
> @jingxu97 is the vendor/modules.txt file missing? https://golang.org/ref/mod#vendoring

I checked, it is included?
https://github.com/kubernetes-csi/csi-proxy/blob/f28d7f58f3f25687173e4c13cb2b87de9cef2ed2/vendor/modules.txt

**Comment by ddebroy** [comment]
Sorry missed that - indeed it is already there.

**Pull request merged**
