### PR TITLE
test: add windows unit test pipeline

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
test: add windows unit test pipeline

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by ddebroy** [comment]
Thanks for the PR @andyzhangx . Is this supposed to run on top of https://github.com/kubernetes-csi/csi-proxy/blob/master/.prow.sh ?

**Comment by andyzhangx** [comment]
> Thanks for the PR @andyzhangx . Is this supposed to run on top of https://github.com/kubernetes-csi/csi-proxy/blob/master/.prow.sh ?

@ddebroy I don't think so, prow is running as a Linux container now.

**Comment by andyzhangx** [comment]
> Thanks for the PR @andyzhangx . Is this supposed to run on top of https://github.com/kubernetes-csi/csi-proxy/blob/master/.prow.sh ?

@ddebroy could you approve, I think we could merge it first since it's just a test config.

**Pull request merged**
