### PR TITLE
Rename Smb to SMB

### LINKED ISSUE #246: Rename Smb and smb to SMB throughout the codebase

### PR DESCRIPTION
**Pull request by alexander-ding**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Improve naming consistency and adhere to Go best practices (using all caps when the name contains acronyms).

**Which issue(s) this PR fixes**:

Fixes #246

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @mauriciopoppe

### CODE REVIEW

**Review by mauriciopoppe — COMMENTED** [review]
I saw `=== RUN   TestNewSMBGlobalMapping` in the unit tests and `=== RUN   TestSMB
--- PASS: TestSMB (20.37s)` in the integration tests in both Github Actions and Prow.

I saw formatting errors that were in the output but the job didn't fail, could you find out why? https://github.com/kubernetes-csi/csi-proxy/actions/runs/3269029089/jobs/5376115868#step:4:40

**Comment by alexander-ding** [comment]
> I saw `=== RUN TestNewSMBGlobalMapping` in the unit tests and `=== RUN TestSMB --- PASS: TestSMB (20.37s)` in the integration tests in both Github Actions and Prow.

Wait, what's wrong with that exactly? The former is a unit test (amongst some other unit tests in the original codebase). The latter
is the integration test. 
 
> I saw formatting errors that were in the output but the job didn't fail, could you find out why? https://github.com/kubernetes-csi/csi-proxy/actions/runs/3269029089/jobs/5376115868#step:4:40

These formatting errors have been happening since long ago (see [this old job](https://github.com/kubernetes-csi/csi-proxy/actions/runs/3110507943/jobs/5041764177)). I think what's happening is that most developers are using Linux/Darwin machines, and gofmt on these machines use \n endings, whereas the GH action runs on a Windows machine, where gofmt looks for \r\n endings. See [this GH issue](https://github.com/golang/go/issues/2242). 

Apparently, that's a feature, not a bug. We can either (a) remove go-fmt checks entirely or (b) migrate them into a separate GH action job. I'd lean towards the other one. 

The reason why this wasn't failing the GH action is because the default behavior is to continue execution (and base the result of the GH action based on the last executed command). See [this post](https://stackoverflow.com/questions/62996357/stop-multiline-github-action-on-first-fail).

**Comment by alexander-ding** [comment]
What I recommend we do right now is to 
1. Ignore the formatting error and merge for now.
2. Track the need to refactor the GitHub action job (and the Makefile) in another issue. We can talk about which way to refactor is best as well.

**Comment by mauriciopoppe** [comment]
Got it, thanks for pointing out the default behavior of Github Actions, yes it looks like this error has been happening for some time already. Changing release-tools is not that easy as the code is common to many kubernetes-csi repos and comes from https://github.com/kubernetes-csi/csi-release-tools/

/lgtm
/approve

**Pull request merged**
