### PR TITLE
master: update release-tools

### PR DESCRIPTION
**Pull request by pohly**
Commit summary:
43e50d6 prow.sh: enable building arm64 image
3df86b7 cloud build: k8s-staging-sig-storage
db0c2a7 cloud build: initialize support for running commands in Dockerfile
340e082 build.make: optional inclusion of Windows in multiarch images
5231f05 build.make: properly declare push-multiarch
4569f27 build.make: fix push-multiarch ambiguity
bd41690 cloud build: initial set of shared files
6f2322e Update patch release notes generation command
d8c76fe Support local snapshot RBAC for pull jobs
ea1f94a update release tools instructions

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
cc @jingxu97

**Comment by pohly** [comment]
Will be replaced with a new PR.

**Comment by jingxu97** [comment]
@pohly do you have a new PR for this? Thank you!

**Comment by pohly** [comment]
See https://github.com/kubernetes-csi/csi-proxy/pull/60

**Pull request closed without merging**
