### PR TITLE
Generate v1 files from latest beta versions

### PR DESCRIPTION
**Pull request by mauriciopoppe**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind feature

**What this PR does / why we need it**:

Generates v1 API files for `client/api/{disk,filesystem,smb,volume}`, summary of changes:

- I copied the beta folders to v1, regenerated the proto & _generated.go files with `make clean` and `make generate`
- I updated the integration tests & unit tests to use the v1 dir
- Also had to force push the v1 files from the vendor directory

/cc @jingxu97 

**Does this PR introduce a user-facing change?**:
```release-note
v1 API version bump for Disk, Volume, FileSystem and SMB API groups
```

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
/cc @ddebroy 
I followed https://github.com/kubernetes-csi/csi-proxy/pull/76

**Comment by mauriciopoppe** [comment]
@jingxu97 @ddebroy the `vendor` folder has a reference to this repository i.e. to `github.com/kubernetes-csi/csi-proxy`, is this correct?

**Comment by ddebroy** [comment]
hey @jingxu97 I know you introduced the vendor directory in https://github.com/kubernetes-csi/csi-proxy/pull/82 and that included the csi-proxy code itself there as well. Do you recall why we need the csi-proxy files in vendor however?

**Comment by ddebroy** [comment]
sorry for the late review. @mauriciopoppe one q I had was are the renaming of the client_generated.go files for the different API groups like: https://github.com/kubernetes-csi/csi-proxy/pull/120/files#diff-9462bc31a89a73f4209384d57c5e6728708a03d7e03d4f2a80e250e2893f887c . Those should be just fresh new files for v1 (as in https://github.com/kubernetes-csi/csi-proxy/tree/master/client/groups/disk for example). Can you please double check that? Otherwise LGTM.

**Comment by mauriciopoppe** [comment]
got it, I see the following in my editor
image
but I also see that it shows as renamed in github, I'll check it

**Comment by mauriciopoppe** [comment]
It looks like git thinks that a vendor file was renamed to the v1 file

image

The vendor files for the usage of v1beta1 and v1beta2 are gone (I regenerated them with `go mod vendor`), I checked the branch for the autogenerated files and both v1beta and v1 are there, so I think we're good :)

**Comment by mauriciopoppe** [comment]
@ddebroy I found out that `client/` is a go module, there's a detailed PR about the why here https://github.com/kubernetes-csi/csi-proxy/pull/7 (to prove this I removed the `go.{mod,sum}` files in `client/` and run `go mod vendor` and there were no references in `vendor/` to `client/`) it's a nested module other directories must include and this was done through `replace`

It looks like the line 

https://github.com/kubernetes-csi/csi-proxy/blob/cf66b0576b4b8b1dbfe4e36bd5b778ffb0e176d0/go.mod#L6

can't be removed, because the source code files are now using the `v1` api some references to `v1betaX` were removed from `modules.txt`

I also looked at the issue about git thinking that a rename happened instead of a code generation, I think this is answered in https://stackoverflow.com/a/15031787/3341726 and it's how diffs are displayed, I run the following to check which files were actually renamed and there are none:

```
❯ git diff --name-status --no-renames master
A       client/api/disk/v1/api.pb.go
A       client/api/disk/v1/api.proto
A       client/api/filesystem/v1/api.pb.go
A       client/api/filesystem/v1/api.proto
A       client/api/smb/v1/api.pb.go
A       client/api/smb/v1/api.proto
A       client/api/volume/v1/api.pb.go
A       client/api/volume/v1/api.proto
A       client/groups/disk/v1/client_generated.go
A       client/groups/filesystem/v1/client_generated.go
A       client/groups/smb/v1/client_generated.go
A       client/groups/volume/v1/client_generated.go
M       go.mod
M       go.sum
M       integrationtests/disk_test.go
M       integrationtests/filesystem_test.go
A       client/api/disk/v1/api.pb.go
A       client/api/disk/v1/api.proto
A       client/api/filesystem/v1/api.pb.go
A       client/api/filesystem/v1/api.proto
A       client/api/smb/v1/api.pb.go
A       client/api/smb/v1/api.proto
A       client/api/volume/v1/api.pb.go
A       client/api/volume/v1/api.proto
A       client/groups/disk/v1/client_generated.go
A       client/groups/filesystem/v1/client_generated.go
A       client/groups/smb/v1/client_generated.go
A       client/groups/volume/v1/client_generated.go
M       go.mod
M       go.sum
M       integrationtests/disk_test.go
M       integrationtests/filesystem_test.go
M       integrationtests/iscsi_test.go
M       integrationtests/smb_test.go
M       integrationtests/volume_test.go
M       internal/server/disk/api_group_generated.go
A       internal/server/disk/internal/v1/conversion.go
A       internal/server/disk/internal/v1/conversion_generated.go
A       internal/server/disk/internal/v1/server_generated.go
M       internal/server/filesystem/api_group_generated.go
A       internal/server/filesystem/internal/v1/conversion.go
A       internal/server/filesystem/internal/v1/conversion_generated.go
A       internal/server/filesystem/internal/v1/server_generated.go
M       internal/server/filesystem/server_test.go
M       internal/server/smb/api_group_generated.go
A       internal/server/smb/internal/v1/conversion.go
A       internal/server/smb/internal/v1/conversion_generated.go
A       internal/server/smb/internal/v1/server_generated.go
M       internal/server/smb/server_test.go
M       internal/server/volume/api_group_generated.go
A       internal/server/volume/internal/v1/conversion.go
A       internal/server/volume/internal/v1/conversion_generated.go
A       internal/server/volume/internal/v1/server_generated.go
M       internal/server/volume/server_test.go
M       release-tools/README.md
M       release-tools/build.make
M       release-tools/cloudbuild.yaml
M       release-tools/prow.sh
D       release-tools/travis.yml
M       release-tools/verify-go-version.sh
A       vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1/api.pb.go
A       vendor/github.com/kubernetes-csi/csi-proxy/client/api/disk/v1/api.proto
```

Anyways it looks like it's just a `git diff` thing, not a codebase problem

**Comment by ddebroy** [comment]
Thanks for double checking that @mauriciopoppe 
/lgtm
/approve

**Pull request merged**
