### PR TITLE
Skip resizing volume when extent is less than the minimum of 1MB.

### PR DESCRIPTION
**Pull request by cphvmware**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR is skipping resize of the volume when extent is less than the minimum of 1MB

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-csi/csi-proxy/issues/195

**Special notes for your reviewer**:
Validated changes with vSphere CSI Driver. Volume is getting expanded when the volume is resized before creating a filesystem on it.

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by cphvmware** [comment]
This fixes merge issue from PR #196

**Comment by mauriciopoppe** [comment]
We're going to make some changes in the branches, after I move the current development to a different branch and v1.x back to master then I think I can enable the tests for this PR

**Comment by cphvmware** [comment]
Yes, I noticed that I can't build csi-proxy right now.

**Comment by mauriciopoppe** [comment]
[cphvmware](https://github.com/cphvmware) we moved some branch around and now:

- `master` points to the current client/server implementation
- `library-development` points to the ongoing HostProcess Pod development

I think you might need to cherrypick your commit on top of the new tip of master, sorry about that!

**Pull request closed without merging**
