### PR TITLE
Changelog for v1.1.0

### PR DESCRIPTION
**Pull request by ddebroy**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Changelog for v1.1.0 release to roll out v2alpha1 API updates.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
how do you generate the changelog? is it with the same tool as CSI https://github.com/kubernetes-csi/csi-release-tools/blob/master/SIDECAR_RELEASE_PROCESS.md#release-process?

**Comment by ddebroy** [comment]
yeah - I do reword quite a bit though :-)

**Pull request merged**
