### PR TITLE
Add a new disk function GetDiskNumberByName in disk v1alpha2 api

### PR DESCRIPTION
**Pull request by jingxu97**
Add disk function GetDiskNumberByName to v1alpha2 api

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by msau42** [comment]
Do we need a new v1alpha2 already? We haven't officially released a v1alpha1 yet right?

**Comment by ddebroy** [comment]
The new API version is based on the decision to always group enhancements/additions to an existing API group in a new API version: https://github.com/kubernetes-csi/csi-proxy/blob/master/client/api/README.md#how-to-add-a-new-version-to-an-existing-api-group

**Comment by msau42** [comment]
That policy makes sense when something is released and we want to retain backwards compatibility.

However in the case this project is still under development and hasn't officially released anything yet.  I think until something is released it makes more sense to keep adding to the API group that's under development. That way you can split up development in phases and/or amongst people, as well as refining the API after testing

**Comment by jingxu97** [comment]
close this in favor of #31

**Pull request closed without merging**
